options:
  image:
    description: |
      Image used to run code preparation and application
    type: string
    default: "python:3.9-slim"
  entrypoint:
    description: |
      Application entrypoint for gunicorn
    type: string
    default: "wsgi:app"
  database_name:
    description: |
      Database name if needed, keep empty if it's not needed
    type: string
    default: ""
  git_repo:
    description: |
      Publicly available git repository, only HTTPS is supported
    type: string
    default: "https://github.com/kirek007/python-hello-web.git"
  application_port:
    description: |
      Application port for internal listening
    type: string
    default: "5000"
  gunicorn_workers:
    description: |
      Workers count
    type: string
    default: "4"